name: path_provider_android
publish_to: none
description: Android implementation of the path_provider plugin.
repository: https://github.com/flutter/packages/tree/main/packages/path_provider/path_provider_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+path_provider%22
version: 2.2.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: path_provider
    platforms:
      android:
        package: io.flutter.plugins.pathprovider
        pluginClass: PathProviderPlugin
        dartPluginClass: PathProviderAndroid

dependencies:
  flutter:
    sdk: flutter
  path_provider_platform_interface: 
    git: https://github.com/kumsumit/path_provider_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git
  test: ^1.16.0

topics:
  - files
  - path-provider
  - paths
